### ISSUE TITLE
release版下载失败.Message: unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by kangjinwen** [rty813/doc_downloader#14]
D:\docDownloader>docDownloader.exe
请输入网址（输入exit退出）：https://max.book118.com/html/2019/1210/6155102204002131.shtm
Traceback (most recent call last):
  File "docDownloader.py", line 44, in <module>
  File "site-packages\fire\core.py", line 138, in Fire
  File "site-packages\fire\core.py", line 463, in _Fire
  File "site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
  File "docDownloader.py", line 20, in main
  File "book118.py", line 22, in download
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

[13500] Failed to execute script docDownloader

===================================================
已安装py,nodejs,R语言环境.

**Comment by rty813** [comment]
有没有安装chrome浏览器

**Comment by kangjinwen** [comment]
> 有没有安装chrome浏览器    之前没有,现在安装了,提示这个...

请输入网址（输入exit退出）：https://max.book118.com/html/2019/1210/6155102204002131.shtm

DevTools listening on ws://127.0.0.1:52424/devtools/browser/1a239df3-2e79-4f19-8da5-daf846148471
Traceback (most recent call last):
  File "docDownloader.py", line 44, in <module>
  File "site-packages\fire\core.py", line 138, in Fire
  File "site-packages\fire\core.py", line 463, in _Fire
  File "site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
  File "docDownloader.py", line 20, in main
  File "book118.py", line 22, in download
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 86
Current browser version is 90.0.4430.72 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

[22864] Failed to execute script docDownloader

**Comment by rty813** [comment]
已经修复，重新下载v1.2.1版本即可
