### ISSUE TITLE
能打开chrome,不能转pdf

### ISSUE THREAD

**Issue by jefflou** [rty813/doc_downloader#21]
下面是提示信息
Traceback (most recent call last):
  File "docDownloader.py", line 44, in <module>
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "docDownloader.py", line 16, in main
  File "doc88.py", line 43, in download
  File "selenium\webdriver\remote\webelement.py", line 80, in click
  File "selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="surplus-btn" id="continueButton">...</div> is not clickable at point (479, 8). Other element would receive the click: <div class="toolbar" id="toolbar" style="position: fixed; width: 100%;">...</div>
  (Session info: chrome=93.0.4577.82)

[4656] Failed to execute script docDownloader

**Comment by rty813** [comment]
你下载的是哪个文档？发一下链接

**Comment by CalmLong** [comment]
DevTools listening on ws://127.0.0.1:57329/devtools/browser/1b5f8f35-dbf4-444f-866d-30c138aceb1a
道客巴巴: 《金属切削原理与刀具（全套课件336P） ppt课件 - 道客巴巴》
Traceback (most recent call last):
  File "docDownloader.py", line 44, in <module>
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "docDownloader.py", line 16, in main
  File "doc88.py", line 48, in download
  File "selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
  File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="readshop"]"}
  (Session info: chrome=94.0.4606.54)

[16980] Failed to execute script docDownloader

**Comment by CalmLong** [comment]
https://www.doc88.com/p-1972503728134.html

**Comment by rty813** [comment]
参考 #22
